// GENERATED by scripts/build_fx_atlas.py — do not edit, rerun instead.

/// Pixel rect of the atlas as UVs.
const fn region(x: f32, y: f32, width: f32, height: f32) -> Rect {
    Rect {
        min: Vec2::new(x / 2048.0, y / 2048.0),
        max: Vec2::new((x + width) / 2048.0, (y + height) / 2048.0),
    }
}

#[allow(dead_code)]
pub const EXPLOSION: SpriteAnim = SpriteAnim {
    rect: region(0.0, 0.0, 800.0, 1128.0),
    frames: 16,
    columns: 4,
    fps: 20.0,
};

#[allow(dead_code)]
pub const FIRETRAIL: SpriteAnim = SpriteAnim {
    rect: region(800.0, 0.0, 256.0, 832.0),
    frames: 52,
    columns: 4,
    fps: 120.0,
};

#[allow(dead_code)]
pub const FIREWOOSH3: SpriteAnim = SpriteAnim {
    rect: region(1056.0, 0.0, 512.0, 768.0),
    frames: 96,
    columns: 8,
    fps: 60.0,
};

#[allow(dead_code)]
pub const FIREWOOSH: SpriteAnim = SpriteAnim {
    rect: region(0.0, 1128.0, 512.0, 576.0),
    frames: 72,
    columns: 8,
    fps: 60.0,
};

#[allow(dead_code)]
pub const FIREWOOSH2: SpriteAnim = SpriteAnim {
    rect: region(512.0, 1128.0, 512.0, 576.0),
    frames: 72,
    columns: 8,
    fps: 60.0,
};

#[allow(dead_code)]
pub const SADS: SpriteAnim = SpriteAnim {
    rect: region(1024.0, 1128.0, 192.0, 160.0),
    frames: 30,
    columns: 6,
    fps: 180.0,
};

#[allow(dead_code)]
pub const SADSSLOW: SpriteAnim = SpriteAnim {
    rect: region(1024.0, 1128.0, 192.0, 160.0),
    frames: 30,
    columns: 6,
    fps: 60.0,
};

#[allow(dead_code)]
pub const BLOODSPLAT: SpriteAnim = SpriteAnim {
    rect: region(0.0, 1704.0, 1020.0, 128.0),
    frames: 34,
    columns: 17,
    fps: 30.0,
};

#[allow(dead_code)]
pub const BLOODSPLAT2: SpriteAnim = SpriteAnim {
    rect: region(1020.0, 1704.0, 420.0, 128.0),
    frames: 14,
    columns: 7,
    fps: 30.0,
};

#[allow(dead_code)]
pub const WHITE: SpriteAnim = SpriteAnim::single(region(1456.0, 1720.0, 32.0, 32.0));

#[allow(dead_code)]
pub const DROPLET: SpriteAnim = SpriteAnim::single(region(1504.0, 1704.0, 32.0, 32.0));

#[allow(dead_code)]
pub const GORE3: SpriteAnim = SpriteAnim::single(region(1536.0, 1704.0, 27.0, 32.0));

#[allow(dead_code)]
pub const BRTL_D: SpriteAnim = SpriteAnim::single(region(1563.0, 1704.0, 21.0, 21.0));

#[allow(dead_code)]
pub const GORE2: SpriteAnim = SpriteAnim::single(region(1584.0, 1704.0, 12.0, 12.0));

#[allow(dead_code)]
pub const BRTL_A: SpriteAnim = SpriteAnim::single(region(1596.0, 1704.0, 12.0, 10.0));

#[allow(dead_code)]
pub const BRTL_B: SpriteAnim = SpriteAnim::single(region(1608.0, 1704.0, 11.0, 10.0));

#[allow(dead_code)]
pub const GORE1: SpriteAnim = SpriteAnim::single(region(1619.0, 1704.0, 8.0, 8.0));

#[allow(dead_code)]
pub const BRTL_C: SpriteAnim = SpriteAnim::single(region(1627.0, 1704.0, 8.0, 7.0));
