#!/usr/bin/env python3
"""Compile fx_sources/*.png into the FX atlas and its Rust region consts.

    fx_sources/explosion.4x4@20.png   ->  pub const EXPLOSION (4 cols, 4 rows, 20 fps)
    fx_sources/logo.png               ->  pub const LOGO (single frame)

Filename convention: `name.<cols>x<rows>@<fps>.png` for spritesheets (every
cell is a frame, left-to-right then top-to-bottom); a plain `name.png` is a
single static frame. A 64x64 solid-white block (WHITE) is always added for
trail ribbons and tinted particles.

Outputs assets/textures/fx_atlas.png and src/fx_atlas.rs. Rerun after adding
or changing sources. If the packer reports overflow, raise SIZE below — the
generated Rust stays in sync automatically.
"""

import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SIZE = 2048

NAME_RE = re.compile(r"(?P<name>[A-Za-z][A-Za-z0-9_]*)(?:\.(?P<cols>\d+)x(?P<rows>\d+)@(?P<fps>\d+(?:\.\d+)?))?")


def main():
    entries = []  # (name, image, cols, rows, fps)
    for path in sorted((ROOT / "fx_sources").glob("*.png")):
        match = NAME_RE.fullmatch(path.stem)
        if not match:
            sys.exit(f"{path.name}: expected `name.png` or `name.<cols>x<rows>@<fps>.png`")
        cols = int(match["cols"] or 1)
        rows = int(match["rows"] or 1)
        fps = float(match["fps"] or 0)
        entries.append((match["name"], Image.open(path).convert("RGBA"), cols, rows, fps))
    entries.append(("white", Image.new("RGBA", (64, 64), (255, 255, 255, 255)), 1, 1, 0.0))

    # Shelf packing: tallest first, fill rows left to right.
    atlas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    consts = []
    x = y = shelf = 0
    for name, image, cols, rows, fps in sorted(entries, key=lambda e: -e[1].height):
        w, h = image.size
        if x + w > SIZE:
            x, y, shelf = 0, y + shelf, 0
        if x + w > SIZE or y + h > SIZE:
            sys.exit(f"{name} ({w}x{h}) does not fit; raise SIZE in {Path(__file__).name}")
        atlas.paste(image, (x, y))
        shelf = max(shelf, h)

        if name == "white":
            # Inset so no neighbor can ever bleed into the solid color.
            rect = f"region({x + 16}.0, {y + 16}.0, 32.0, 32.0)"
        else:
            rect = f"region({x}.0, {y}.0, {w}.0, {h}.0)"
        if cols * rows > 1:
            consts.append(
                f"#[allow(dead_code)]\npub const {name.upper()}: SpriteAnim = SpriteAnim {{\n"
                f"    rect: {rect},\n    frames: {cols * rows},\n    columns: {cols},\n    fps: {fps},\n}};"
            )
        else:
            consts.append(
                f"#[allow(dead_code)]\npub const {name.upper()}: SpriteAnim = SpriteAnim::single({rect});"
            )
        x += w

    atlas.save(ROOT / "assets/textures/fx_atlas.png")
    (ROOT / "src/fx_atlas.rs").write_text(
        "// GENERATED by scripts/build_fx_atlas.py — do not edit, rerun instead.\n\n"
        "/// Pixel rect of the atlas as UVs.\n"
        "const fn region(x: f32, y: f32, width: f32, height: f32) -> Rect {\n"
        "    Rect {\n"
        f"        min: Vec2::new(x / {SIZE}.0, y / {SIZE}.0),\n"
        f"        max: Vec2::new((x + width) / {SIZE}.0, (y + height) / {SIZE}.0),\n"
        "    }\n}\n\n" + "\n\n".join(consts) + "\n"
    )
    print(f"packed {len(entries)} sheets into assets/textures/fx_atlas.png + src/fx_atlas.rs")


if __name__ == "__main__":
    main()
